import { CustomerModel } from './customer.model';

export let customerData: CustomerModel[] = [
  {
    customerNo: 34,
    name: 'Kovács János',
    address: 'József Attila u. 1.',
    city: 'Budapest',
    state: 'Pest',
    country: 'Magyarország',
  },
  {
    customerNo: 35,
    name: 'Nagy Béla',
    address: 'Petőfi Sándor u. 2.',
    city: 'Budapest',
    state: 'Pest',
    country: 'Magyarország',
  },
  {
    customerNo: 36,
    name: 'Kiss Pál',
    address: 'Kossuth Lajos u. 3.',
    city: 'Kecskemét',
    state: 'Bács-Kiskun',
    country: 'Magyarország',
  },
  {
    customerNo: 37,
    name: 'Kissné Pál',
    address: 'Kossuth Lajos u. 3.',
    city: 'Kecskemét',
    state: 'Bács-Kiskun',
    country: 'Magyarország',
  },
  {
    customerNo: 38,
    name: 'Nagyné Béla',
    address: 'Petőfi Sándor u. 2.',
    city: 'Kecskemét',
    state: 'Bács-Kiskun',
    country: 'Magyarország',
  },
  {
    customerNo: 39,
    name: 'Kovácsné János',
    address: 'József Attila u. 1.',
    city: 'Budapest',
    state: 'Pest',
    country: 'Magyarország',
  },
  {
    customerNo: 40,
    name: 'Jónás János',
    address: 'József Attila u. 1.',
    city: 'Budapest',
    state: 'Pest',
    country: 'Magyarország',
  },
];
